name: "Snyk Terraform Scan"
on:
  workflow_call:

permissions:
  security-events: write
  contents: read

jobs:
  snyk-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Run Snyk for terraform
        id: snyk
        uses: snyk/actions/iac@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: >-
            --sarif-file-output=terraform/terraform-snyk.sarif
            --severity-threshold=high
            --fail-on=all
          sarif: false
          file: .terraform/

      - name: Upload SARIF results
        if: steps.snyk.outcome == 'failure'
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: terraform/terraform-snyk.sarif
