name: "Snyk Terraform Scan"
on:
  workflow_call:
    secrets:
      SNYK_TOKEN:
        required: true

permissions:
  security-events: write
  contents: read
  actions: read

jobs:
  snyk-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # - name: Run Snyk for terraform
      #   id: snyk
      #   uses: snyk/actions/iac@master
      #   continue-on-error: true
      #   env:
      #     SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      #   with:
      #     args: >-
      #       --sarif-file-output=terraform/terraform-snyk.sarif
      #       --severity-threshold=high
      #       --fail-on=all
      #     file: terraform/

      - name: Install Snyk CLI
        uses: snyk/actions/setup@master

      - name: Run Snyk IaC test
        id: snyk
        run: |
          # generate both SARIF and JSON report (always writes SARIF)
          snyk iac test terraform/ \
            --sarif-file-output=terraform/terraform-snyk.sarif \
            --json > terraform/terraform-snyk.json 2>&1 || true

          # fail if any "high" severity is present
          if grep -q '"severity":"high"' terraform/terraform-snyk.json; then
            echo "⚠️ High severity IaC issues detected!"
            exit 1
          fi
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Check SARIF exists
        id: sarif-check
        run: |
          if [ -f terraform/terraform-snyk.sarif ]; then
           echo "exists=true" >> "$GITHUB_OUTPUT"
          else
           echo "exists=false" >> "$GITHUB_OUTPUT"
           exit 1
          fi

      - name: Upload SARIF results
        if: steps.sarif-check.outputs.exists == 'true'
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: terraform/terraform-snyk.sarif
